# Generated by Django 3.0.3 on 2020-07-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='No email id', max_length=25, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('course', models.CharField(max_length=20)),
                ('fee', models.IntegerField()),
                ('dateofJoining', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='studentpics')),
            ],
        ),
    ]
