# Generated by Django 3.0.8 on 2020-07-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(default='', max_length=25, unique=True),
        ),
    ]
